# Generated by Django 3.2.3 on 2021-05-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('text', models.TextField(help_text='Enter your post here')),
                ('created_at', models.DateTimeField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.user')),
                ('parent_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.post')),
            ],
            options={
                'ordering': ['parent_id', 'created_at'],
            },
        ),
    ]
