# Generated by Django 3.2.3 on 2021-05-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_id', to='catalog.post'),
        ),
    ]
