# Generated by Django 3.2.3 on 2021-05-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_post_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='catalog.post'),
        ),
    ]
